name: Python Tests

on:
  push:
    branches:
      - main  # Trigger tests when pushing to the main branch
  pull_request:
    branches:
      - main  # Trigger tests when creating a pull request to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # Specify the Python version you want to use

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      # Run the unit tests using pytest
      - name: Run unit tests
        run: |
          pytest Project1-GeoLocationMatching/test_geolocation.py  # Correct path to the test file
